### ISSUE TITLE
Can this work with more cartoonish art styles?

### ISSUE THREAD

**Issue by Njasa2k** [PairCustomization/PairCustomization#6]
I've noticed that you've tried more photorealistic art styles and I was wondering if this can this work with more cartoonish art styles where the structure is not necessarily the same as the content image.

**Comment by PairCustomization** [comment]
Hi,
Thanks for the question! The method should work for pairs where content is not exactly preserved - When evaluating trained models on such pairs, I would first try:
(1) Generating images with the same/similar content/style prompt to the one used during training as a litmus test
(2) Trying higher style guidance values for more content change (for instance, if CFG scale is 5 you may try style guidance scale 4 or even 6)

All prompts should exhibit some effect with high enough style guidance, but these initial tests are a good way to make sure the weights have been trained correctly.

Hope that helps!
