### ISSUE TITLE
No module named 'diffusers.models.dual_transformer_2d'

### ISSUE THREAD

**Issue by euminds** [PairCustomization/PairCustomization#7]
I meet an issue, No module named 'diffusers.models.dual_transformer_2d'
![image](https://github.com/PairCustomization/PairCustomization/assets/46481864/ae52d14c-7baa-4554-b540-6711d4c8ce66)

My setup is as following:
```
 conda create -n PCUS python=3.10
conda activate PCUS
cd PairCustomization
pip install -r requirements.txt
accelerate config
bash 
 ```
accelerate env
```
- `Accelerate` version: 0.30.1
- Platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.35
- `accelerate` bash location: /home/jintao/miniconda3/envs/PCUS/bin/accelerate
- Python version: 3.10.14
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.3.0+cu121 (False)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- System RAM: 62.50 GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: NO
        - mixed_precision: fp16
        - use_cpu: False
        - debug: False
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: 0
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - enable_cpu_affinity: False
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
 ```
and running

 ```
 bash training_scripts/train_pair_customization_lora_sdxl.sh
 ```

**Comment by euminds** [comment]
> I meet an issue, No module named 'diffusers.models.dual_transformer_2d' ![image](https://private-user-images.githubusercontent.com/46481864/334634627-ae52d14c-7baa-4554-b540-6711d4c8ce66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NTIzNTYsIm5iZiI6MTcxNjk1MjA1NiwicGF0aCI6Ii80NjQ4MTg2NC8zMzQ2MzQ2MjctYWU1MmQxNGMtN2JhYS00NTU0LWI1NDAtNjcxMWQ0YzhjZTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAzMDczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNDJmNzY3ODI2MmZkOGI1MzhkNmM3M2U3NjkyMWVmMmVlOGZkYWJhMGU4YTgzZGJjMmVkM2IyMDdiMjhlYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GgrGSNstGYydsnU7QynvvnIurdGx3cx90BIm3vVgCjc)
> 
> My setup is as following:
> 
> ```
>  conda create -n PCUS python=3.10
> conda activate PCUS
> cd PairCustomization
> pip install -r requirements.txt
> accelerate config
> bash 
> ```
> 
> accelerate env
> 
> ```
> - `Accelerate` version: 0.30.1
> - Platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.35
> - `accelerate` bash location: /home/jintao/miniconda3/envs/PCUS/bin/accelerate
> - Python version: 3.10.14
> - Numpy version: 1.26.4
> - PyTorch version (GPU?): 2.3.0+cu121 (False)
> - PyTorch XPU available: False
> - PyTorch NPU available: False
> - PyTorch MLU available: False
> - System RAM: 62.50 GB
> - `Accelerate` default config:
>         - compute_environment: LOCAL_MACHINE
>         - distributed_type: NO
>         - mixed_precision: fp16
>         - use_cpu: False
>         - debug: False
>         - num_processes: 1
>         - machine_rank: 0
>         - num_machines: 1
>         - gpu_ids: 0
>         - rdzv_backend: static
>         - same_network: True
>         - main_training_function: main
>         - enable_cpu_affinity: False
>         - downcast_bf16: no
>         - tpu_use_cluster: False
>         - tpu_use_sudo: False
>         - tpu_env: []
> ```
> 
> and running
> 
> ```
> bash training_scripts/train_pair_customization_lora_sdxl.sh
> ```

what's your diffusers version?

**Comment by PairCustomization** [comment]
Maybe try to switch your accelerate/transformers versions to 0.28.0 with
`pip install accelerate==0.28.0 transformers==4.39.3`

when running
`pip show diffusers`
you should get Version: 0.28.0.dev0

**Comment by euminds** [comment]
> I meet an issue, No module named 'diffusers.models.dual_transformer_2d' ![image](https://private-user-images.githubusercontent.com/46481864/334634627-ae52d14c-7baa-4554-b540-6711d4c8ce66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NTI5MjUsIm5iZiI6MTcxNjk1MjYyNSwicGF0aCI6Ii80NjQ4MTg2NC8zMzQ2MzQ2MjctYWU1MmQxNGMtN2JhYS00NTU0LWI1NDAtNjcxMWQ0YzhjZTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAzMTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMTYwNjQ5OTdlNmVjM2Q1ZGI2NmRmMjQxNjhiNjNlZDcwNThkZmZiNGFlYWUzNTE1ZTcxMTVjMWRjNzYwOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OMN5OexLSZDIW3JhfO1jKvDOUNWlVDIzQO8_nlGnZwc)
> 
> My setup is as following:
> 
> ```
>  conda create -n PCUS python=3.10
> conda activate PCUS
> cd PairCustomization
> pip install -r requirements.txt
> accelerate config
> bash 
> ```
> 
> accelerate env
> 
> ```
> - `Accelerate` version: 0.30.1
> - Platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.35
> - `accelerate` bash location: /home/jintao/miniconda3/envs/PCUS/bin/accelerate
> - Python version: 3.10.14
> - Numpy version: 1.26.4
> - PyTorch version (GPU?): 2.3.0+cu121 (False)
> - PyTorch XPU available: False
> - PyTorch NPU available: False
> - PyTorch MLU available: False
> - System RAM: 62.50 GB
> - `Accelerate` default config:
>         - compute_environment: LOCAL_MACHINE
>         - distributed_type: NO
>         - mixed_precision: fp16
>         - use_cpu: False
>         - debug: False
>         - num_processes: 1
>         - machine_rank: 0
>         - num_machines: 1
>         - gpu_ids: 0
>         - rdzv_backend: static
>         - same_network: True
>         - main_training_function: main
>         - enable_cpu_affinity: False
>         - downcast_bf16: no
>         - tpu_use_cluster: False
>         - tpu_use_sudo: False
>         - tpu_env: []
> ```
> 
> and running
> 
> ```
> bash training_scripts/train_pair_customization_lora_sdxl.sh
> ```

Do you provide the project environment.yaml?  follow
```
conda env export > environment.yaml
```

**Comment by euminds** [comment]
> Maybe try to switch your accelerate/transformers versions to 0.28.0 with `pip install accelerate==0.28.0 transformers==4.39.3`
> 
> when running `pip show diffusers` you should get Version: 0.28.0.dev0

Thank you, i have run Paircustomization. It's my requirements.txt

```
--extra-index-url https://download.pytorch.org/whl/cu118
accelerate==0.28.0
torch>=2.0.1
torchvision
transformers==4.39.3
ftfy
tensorboard
Jinja2
peft>=0.10.0
# git+https://github.com/huggingface/diffusers
diffusers==0.28.0
```
