### ISSUE TITLE
how to train StableDiffusionXLImg2ImgPipelineLora

### ISSUE THREAD

**Issue by whcjb** [PairCustomization/PairCustomization#8]
hello, i find the code evaluation has the StableDiffusionXLImg2ImgPipelineLora, but how to train the pipeline? thank you.

**Comment by PairCustomization** [comment]
you shouldn't need to train the pipeline - here the trained portion is the low rank adapters that we add to the pipeline: https://github.com/PairCustomization/PairCustomization/blob/main/evaluation_scripts/evaluate_real_image.py#L84

hope that clears up any confusion!
