### ISSUE TITLE
Question in Training image 

### ISSUE THREAD

**Issue by wrtg666** [PairCustomization/PairCustomization#9]
I wonder in each image pair for training, for to gain these pairs?
Can I just use other model to generate a stylized image based on an real image. Then train using this pair?

**Comment by PairCustomization** [comment]
Yep that will work! For the paper, in addition to using real pairs from artists (with permission), I used a few different models to generate styled images. Of these, the most accessible is [LEDITS++](https://huggingface.co/spaces/editing-images/leditsplusplus)

**Comment by wrtg666** [comment]
OK, I find it hard to search for real pairs. lol.
Any keyword or channel for searching?
